apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: ${{ values.description | dump }}
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner | dump }}
